ZDOTDIR=$HOME/.config/zsh
EDITOR=nvim

TYPEWRITTEN_PROMPT_LAYOUT="singleline_verbose"
TYPEWRITTEN_RELATIVE_PATH="adaptive"

[[ -v DISTROBOX_ENTER_PATH ]] && \
    LANG=en_US.UTF-8 \
    LC_NUMERIC=fi_FI.UTF-8 \
    LC_TIME=fi_FI.UTF-8 \
    LC_MONETARY=fi_FI.UTF-8 \
    LC_PAPER=fi_FI.UTF-8 \
    LC_MEASUREMENT=fi_FI.UTF-8
