vim.g.mapleader = ' '

vim.keymap.set('n', '<leader>bb', '<Cmd>Telescope buffers<CR>')
vim.keymap.set('n', '<Leader>fc', '<Cmd>Telescope commands<CR>')
vim.keymap.set('n', '<Leader>fr', '<Cmd>Telescope oldfiles<CR>')
vim.keymap.set('n', '<Leader>ff', '<Cmd>Telescope find_files<CR>')
vim.keymap.set('n', '<Leader>fF', ':lua require"telescope.builtin".find_files{ cwd = "./" }<Left><Left><Left>')
vim.keymap.set('n', '<Leader>fg', '<Cmd>Telescope live_grep<CR>')
vim.keymap.set('n', '<Leader>fb', '<Cmd>Telescope file_browser<CR>')
vim.keymap.set('n', '-', '<Cmd>Telescope file_browser cwd=%:p:h<CR>')
vim.keymap.set('n', '<Leader>fh', '<Cmd>Telescope help_tags<CR>')
vim.keymap.set('n', '<Leader>f/', '<Cmd>Telescope search_history<CR>')
vim.keymap.set('n', '<Leader>gB', '<Cmd>Telescope git_branches<CR>')
vim.keymap.set('n', '<Leader>gs', '<Cmd>Telescope git_status<CR>')
vim.keymap.set('n', '<Leader>f.', require'config.telescope'.find_dotfiles)
vim.keymap.set('n', '<Esc>', '<Cmd>nohl<CR><Esc>')
vim.keymap.set('n', '<leader>bd', function () require'bufdelete'.bufdelete(0) end)
vim.keymap.set('n', '<Leader>gg', '<Cmd>Git<CR>')
vim.keymap.set('n', '<Leader>gb', '<Cmd>Git blame<CR>')
vim.keymap.set('n', '<Leader>gl', '<Cmd>Git log<CR>')
vim.keymap.set('n', '[h', require'gitsigns.actions'.prev_hunk)
vim.keymap.set('n', ']h', require'gitsigns.actions'.next_hunk)
vim.keymap.set('n', '<Leader>hb', function () require'gitsigns'.blame_line { full = true } end)
vim.keymap.set('n', '<Leader>hs', require'gitsigns'.stage_hunk)
vim.keymap.set('n', '<Leader>hu', require'gitsigns'.undo_stage_hunk)
vim.keymap.set('n', '<Leader>hp', require'gitsigns'.preview_hunk)
vim.keymap.set('i', '<C-s>', '<C-o>:lua vim.lsp.buf.signature_help()<CR>')
